#!/bin/bash

usage="Usage: robby {start|stop} <mode>"

if [ $# -lt 2 ]; then
    echo "$usage"
    exit 1
fi

cmd=$1
mode=$2

case "$cmd" in
    start)
        python robby.py $mode >start.log 2&>1 &
        ;;

    stop)
        pid=$(ps -ef | grep "robby.py $mode" | grep -v grep | awk '{ print $2 }')
        if [ "$pid" != "" ]; then kill $pid; fi
        ;;

    *)
        echo "$usage"
esac