#!/bin/bash

usage="Usage: robby {run|start|stop} <mode>"

if [ $# -lt 2 ]; then
    echo "$usage"
    exit
fi

cmd=$1
mode=$2

case "$cmd" in
    run)
        python robby.py $mode
        ;;

    start)
        python robby.py $mode >start.log 2&>1 &
        ;;

    stop)
        pid=$(ps -ef | grep "robby.py $mode" | grep -v grep | awk '{ print $2 }')
        [ "$pid" != "" ] && kill $pid
        ;;

    *)
        echo "$usage"
esac